/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_pixodro_FuriousBlocks */

#ifndef _Included_me_pixodro_FuriousBlocks
#define _Included_me_pixodro_FuriousBlocks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_pixodro_FuriousBlocks
 * Method:    facebookSessionStatusCallback
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_pixodro_FuriousBlocks_facebookSessionStatusCallback
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
