/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_pixodro_FuriousBlocks_SessionStatusCallback */

#ifndef _Included_me_pixodro_FuriousBlocks_SessionStatusCallback
#define _Included_me_pixodro_FuriousBlocks_SessionStatusCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
