#ifndef __BlockState_H_
#define __BlockState_H_


enum class BlockState{ IDLE, SWITCHING_FORTH, DONE_SWITCHING_FORTH, SWITCHING_BACK, HOVERING, DONE_HOVERING, FALLING, BLINKING, DONE_BLINKING, EXPLODING, DONE_EXPLODING, REVEALING, DONE_REVEALING, AIRBOUNCING, DONE_AIRBOUNCING, TO_DELETE};

#endif //__BlockState_H_
